common:
    lid_topic: "/airsim_node/drone_1/lidar"
    imu_topic: "/airsim_node/drone_1/imu/imu"
    time_sync_en: true

preprocess:
    lidar_type: 2
    scan_line: 32
    blind: 4

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree: 360
    det_range: 30.0
    extrinsic_est_en: true
    extrinsic_T: [0.05512, 0.02226, -0.0297]
    extrinsic_R: [1, 0, 0,
                  0, 1, 0,
                  0, 0, 1]

publish:
    path_publish_en: false
    scan_publish_en: true
    dense_publish_en: false
    scan_bodyframe_pub_en: false

pcd_save:
    pcd_save_en: true
    interval: -1

feature_extract_enable: false
point_filter_num: 3
max_iteration: 3
filter_size_surf: 0.5
filter_size_map: 0.5
cube_side_length: 1000

ivox_grid_resolution: 0.5
ivox_nearby_type: 18
esti_plane_threshold: 0.1